apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: practice
type: Opaque
stringData:
  POSTGRES_DB: myapp
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mypassword
  POSTGRES_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: practice
type: Opaque
stringData:
  admin-user: admin
  admin-password: admin
