apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "k8s-practice.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.secrets.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  labels:
    {{- include "k8s-practice.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-user: {{ .Values.secrets.grafana.adminUser | quote }}
  admin-password: {{ .Values.secrets.grafana.adminPassword | quote }}
